apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  DB_URL: "jdbc:postgresql://timescaledb:5432/sensordb" 
  DB_USER: "postgres"  
  DB_PASSWORD: "password123"
  DB_HOST: timescaledb
  PATRONI_SUPERUSER_PASSWORD: "password123"
  PATRONI_REPLICATION_PASSWORD: "password123"
  PATRONI_admin_PASSWORD: "password123"