{
 "title": "IoT Sensor Data Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Temperature Distribution Over Time",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  temperature AS \"Temperature\"\r\nFROM sensor_data\r\nORDER BY timestamp DESC\r\n"
    }
   ]
  },
  {
   "title": "Temperature and Humidity Over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT temperature, humidity, time_bucket('5s', \"timestamp\") AS \"time\"\r\nFROM sensor_data \r\nGROUP BY time, temperature , humidity\r\nORDER BY time desc"
    }
   ]
  },
  {
   "title": "Current Humidity",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT humidity, time_bucket('5s', \"timestamp\") AS \"time\"\r\nFROM sensor_data \r\nGROUP BY time, humidity \r\nORDER BY time desc\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT temperature, time_bucket('5s', \"timestamp\") AS \"time\"\r\nFROM sensor_data \r\nGROUP BY time, temperature \r\nORDER BY time desc\r\nLIMIT 1"
    }
   ]
  }
 ]
}