apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  labels:
    strimzi.io/cluster: my-cluster
  name: dual-role
spec:
  replicas: 1
  roles:
  - controller
  - broker
  storage:
    type: jbod
    volumes:
    - deleteClaim: false
      id: 0
      kraftMetadata: shared
      size: 100Gi
      type: persistent-claim

---

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
  name: my-cluster
  namespace: iot-app
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      default.replication.factor: 1
      min.insync.replicas: 1
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    listeners:
    - configuration:
        brokers:
        - advertisedHost: localhost
          broker: 0
      name: external
      port: 9094
      tls: false
      type: nodeport
    - name: plain
      port: 9092
      tls: false
      type: internal
    - name: tls
      port: 9093
      tls: true
      type: internal
    metadataVersion: 3.8-IV0
    version: 3.8.0