apiVersion: v2
name: iot-sensor-app
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "1.16.0"

dependencies:
  - name: spark-operator
    version: 1.4.6
    repository: https://kubeflow.github.io/spark-operator
  - name: strimzi-kafka-operator
    repository: oci://quay.io/strimzi-helm
    version: 0.43.0  
  - name: timescaledb-single
    version: 0.13.2
    repository: https://charts.timescale.com
  - name: kafka-ui
    version: 0.7.6
    repository: https://provectus.github.io/kafka-ui-charts
  - name: grafana
    version: 8.5.1
    repository: https://grafana.github.io/helm-charts
  - name: emqx
    version: 4.4.12
    repository: https://repos.emqx.io/charts

